---
- name: Lookup Filter example
  hosts: dev 
  vars:
    user_list:
     - name: chandra 
       groups: au374-grp 
       system: No
       shell: /bin/tcsh 

     - name: Prakash
       groups: au375-grp 
       system: No
       shell: /bin/bash 
  tasks:
   - name: Manage user
     #ansible.builtin.user:
     ansible.builtin.debug:
      msg: |
       name: "{{ item['name'] }}"
       groups: "{{ item['groups'] | default(omit) }}" 
       system: "{{ item['system'] | default(false) }}" 
       shell: "{{ item['shell'] | default('/bin/bash') }}" 
       state: "{{ item['state'] | default('present') }}" 
       remove: "{{ item['remove'] | default(false) }}" 
     loop: "{{ user_list }}" 
