---
- name: Query & loop
  hosts: localhost
  gather_facts: false
  vars:
    file_list: "{{ query('ansible.builtin.file', 'files/file1', 'files/file2', 'files/file1') }}"
  tasks:
    - name: Read from file contents.
      ansible.builtin.debug:
        var:  item 
      loop: "{{ file_list }}" 
  
