---
- name: Task1-01 - Direct task
  ansible.builtin.debug:
    msg: "This is task1-01 - Direct task" 
- name: Task1-02 - Direct task
  ansible.builtin.debug:
    msg: "This is task1-02 - Direct task" 
- name: Task1-03 - Direct task
  ansible.builtin.debug:
    msg: "This is task1-03 - Direct task" 
