---
- name: Simaple playboo 1st  
  hosts: dev 
  gather_facts: true
  tasks:
    - name: Play1-Task-01 
      ansible.builtin.debug:
        msg: "Test"
- name: Simaple playbook 2nd 
  hosts: dev 
  gather_facts: false 
  tasks:
    - name: Play2-Task-01
      ansible.builtin.debug:
        var: ansible_facts
